# Keybinds

# == reload
bind=Super+CTRL,R,reload_config
bind=Super,M,quit
bind=Alt,Q,killclient
# == apps
bind=Super,Q,spawn,foot
bind=Super,W,spawn,librewolf
bind=Super,E,spawn,nautilus
bind=Alt,space,spawn,fuzzel


# == screenshot
bind=Super,Z,spawn_shell,grim $HOME/Pictures/Screenshots/$(date +%Y%m%d%H%M%S).png | wl-copy

bind=Super+Shift,Z,spawn_shell,grim -g "$(slurp -d)" /home/haid/pictures/Screenshots/screenshot.png && grim -g "$(slurp)" - | wl-copy
# == Audio
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# == Brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 1%

# == Playerctl
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause

# === window management ===
# == layouts
bind=Super,n,switch_layout
bind=Super,s,setlayout,scroller
bind=Super+Shift,s,setlayout,tile
# == window focus
bind=Super,Tab,focusstack,next
bind=Super,H,focusdir,left
bind=Super,L,focusdir,right
bind=Super,J,focusdir,down
bind=Super,K,focusdir,up

# == window states
#bind=Alt,Tab,Toggleoverview,
bind=Super,F,togglefullscreen
bind=Super,A,togglemaximizescreen
bind=Super,backslash,togglefloating
bind=Super,S,toggle_scratchpad
# == swap windows
bind=Super+Shift,H,exchange_client,left
bind=Super+Shift,L,exchange_client,right
bind=Super+Shift,J,exchange_client,down
bind=Super+Shift,K,exchange_client,up

# == tag switch
bind=Super,1,view,1,0
bind=Super,2,view,2,0
bind=Super,3,view,3,0
bind=Super,4,view,4,0
bind=Super,5,view,5,0
bind=Super,6,view,6,0
bind=Super,7,view,7,0
bind=Super,8,view,8,0
bind=Super,9,view,9,0

# move window to tag
bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

# == gaps
bind=Alt+Shift,X,incgaps, 1
bind=Alt+Shift,Z,incgaps, -1
bind=Alt+Shift,R,togglegaps

# == resize
bind=Alt,H,resizewin,-50,+0
bind=Alt,L,resizewin,+50,0
bind=Alt,J,resizewin,-50,+0
bind=Alt,K,resizewin,+50,+0

# == Mouse bindings
mousebind=Super,btn_left,moveresize,curmove
mousebind=Super,btn_right,moveresize,curresize
