# exec on startup
exec-once= pipewire &
exec-once= waybar
exec= swaybg -i ~/Wallpaper/wall_scenictrain.jpg
exec-once= wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once= wl-paste --watch cliphist store &

env=QT_QPA_PLATFORMTHEME=qt6ct
# sources
 source = ~/.config/mango/bindings.conf
# source = ~/.config/mango/input.conf
 source = ~/.config/mango/animations.conf
 source = ~/.config/mango/animations.conf
 source = ~/.config/mango/layout.conf
# Window effect
# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us,de
xkb_rules_options=grp:lalt_lshift_toggle

# Trackpad
# need relogin to make it apply
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
mouse_accel_speed=1.0
mouse_accel_profile=1

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
cursor_size=24
cursor_hide_timeout=8
# Appearance
gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=1
rootcolor=0x201b14ff
bordercolor=0x444444ff
dropcolor=0x8FBA7C55
splitcolor=0xEB441EFF
focuscolor=0xc9b890ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:fair
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:fair
tagrule=id:4,layout_name:fair
tagrule=id:5,layout_name:fair
tagrule=id:6,layout_name:fair
tagrule=id:7,layout_name:fair
tagrule=id:8,layout_name:fair
tagrule=id:9,layout_name:fair

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
